---
sysctl_settings_gateway:
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.ipv4.conf.default.rp_filter
    value: 0
  - name: net.ipv4.conf.all.rp_filter
    value: 0
  - name: net.ipv4.neigh.default.gc_thresh1
    value: 1024
  - name: net.ipv4.neigh.default.gc_thresh2
    value: 2048
  - name: net.ipv4.neigh.default.gc_thresh3
    value: 4096
  - name: net.ipv6.conf.all.forwarding
    value: 1
  - name: net.ipv6.conf.all.autoconf
    value: 0
  - name: net.ipv6.conf.default.autoconf
    value: 0
  - name: net.ipv6.conf.all.accept_ra
    value: 0
  - name: net.ipv6.conf.default.accept_ra
    value: 0
  - name: net.ipv6.neigh.default.gc_thresh1
    value: 1024
  - name: net.ipv6.neigh.default.gc_thresh2
    value: 2048
  - name: net.ipv6.neigh.default.gc_thresh3
    value: 4096
