---
- name: install dhcp packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ kea_packages }}"

- name: configure kea dhcp server
  template:
    src: kea_dhcp4.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
  notify: restart kea-dhcp4-server

- name: remove kea init file if present
  file:
    path: /etc/init.d/kea-dhcp4-server
    state: absent
  notify: reload systemd

- name: enable systemd unit kea
  systemd:
    name: kea-dhcp4-server
    enabled: yes
    state: started
