---

- name: install Kea from Debain repository
  include: debian9.yml
  when: ansible_distribution_major_version|int == 9

- name: install Kea from Upsteam repository
  include: upstream.yml
  when: ansible_distribution_major_version|int >= 10
