---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart yanic
  when: server_type == "monitoring"
  systemd:
    name: yanic
    state: restarted

- name: restart respondd
  systemd:
    name: respondd
    state: restarted
