---
- name: install golang package
  apt:
    name: golang
    state: latest
    default_release: stretch-backports

- name: create GOPATH directory
  file:
    path: "{{ gopath }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: set GOPATH globally via profile.d
  template:
    src: go.sh.j2
    dest: /etc/profile.d/go.sh
    owner: root
    group: root
    mode: 0644
