---
- name: install batman-module and linux headers
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - linux-headers-amd64
    - batman-adv-dkms
    - batctl

- name: configure batman module to load on system boot
  template:
    src: batman-adv.module.conf.j2
    dest: /etc/modules-load.d/batman-adv.conf

- name: load batman module
  modprobe:
    name: "batman-adv"
    state: present
