---

#- name: test key concatenation
#  debug: msg=" would/will set keys; {{ mwu_s_admin_keys ~ ( h_v_add_auth_keys | default('') ) }}"

- name: ensure all wanted ssh keys exclusively
  authorized_key: exclusive=True state=present user=admin
              key={{ mwu_s_admin_keys ~ ( h_v_add_auth_keys | default('') ) }}
