---
- name: create dummy interfaces
  template:
    src: dummy.j2
    dest: "/etc/network/interfaces.d/{{ item.key }}0"
  notify: reload network interfaces
  with_dict: "{{ meshes }}"

- name: create batman interfaces
  template:
    src: batman.j2
    dest: "/etc/network/interfaces.d/{{ item.key }}BAT"
  notify: reload network interfaces
  with_dict: "{{ meshes }}"
