---
- name: create dummy interfaces
  template:
    src: dummy.j2
    dest: "/etc/network/interfaces.d/{{ item.id }}0"
  notify: reload network interfaces
  loop: "{{ meshes }}"

- name: create batman interfaces
  template:
    src: batman.j2
    dest: "/etc/network/interfaces.d/{{ item.id }}bat"
  notify: reload network interfaces
  loop: "{{ meshes }}"

- name: flush handlers
  meta: flush_handlers
