---
http_firmware_selector_external: "{{ http_firmware_selector_prefix }}.{{ http_domain_external }}"
http_firmware_selector_internal: "{{ http_firmware_selector_prefix }}.{{ http_domain_internal }}"

firmware_selector_path: "/var/www/firmware_selector"

map_layers:
  - osm_mapnik:
    name: 'OpenStreetMap'
    url: 'https://{{ http_firmware_selector_external }}/tiles/{z}/{x}/{y}.png'
    max_zoom: 19
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
