---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload systemd unit bird
  systemd:
    name: bird
    state: reloaded

- name: reload systemd unit bird6
  systemd:
    name: bird6
    state: reloaded
