---
- name: install radvd packages
  apt:
    name: radvd
    state: present
  notify: reload systemd

- name: enable systemd unit radvd
  systemd:
    name: radvd
    enabled: yes

- name: configure radvd
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
  notify: restart systemd unit radvd
