---
- name: install radvd packages
  package:
    name: radvd
    state: present

- name: configure radvd
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
  notify: restart systemd unit radvd

- name: enable systemd unit radvd
  systemd:
    name: radvd
    enabled: yes
    state: started
