---
- name: configure systemd unit tinc
  systemd:
    name: tinc
    enabled: yes
    daemon_reload: yes

- name: restart systemd unit tinc
  systemd:
    name: tinc
    enabled: yes
    state: restarted
