---
http_media_external: "{{ http_media_prefix }}.{{ http_domain_external }}"
http_media_internal: "{{ http_media_prefix }}.{{ http_domain_internal }}"

media_path: "{{ www_path }}/media"

h5ai_version: "0.29.2"
h5ai_src: "https://release.larsjung.de/h5ai/h5ai-{{ h5ai_version }}.zip"
