---
- name: Add dovecot gpg key.
  apt_key:
    url: "{{ apt_repo_gpg_dovecot }}"
    state: "present"

- name: Add dovecot apt repository.
  apt_repository:
    repo: "{{ item }}"
    state: "present"
    filename: dovecot
  loop: "{{ apt_repo_url_dovecot }}"

- name: Update apt cache.
  apt:
    update_cache: "yes"

- name: Install mail packages.
  apt:
    name: "{{ _mail_packages }}"
    state: "present"

- import_tasks: modoboa.yml
- import_tasks: postfix.yml
- import_tasks: dovecot.yml
- import_tasks: mailman.yml
