---
sysctl_settings_routing_basic:
  - name: net.ipv4.conf.default.rp_filter
    value: 0
  - name: net.ipv4.conf.all.rp_filter
    value: 0
  - name: net.ipv6.conf.all.accept_ra
    value: 0
  - name: net.ipv6.conf.default.accept_ra
    value: 0

sysctl_settings_routing_gateway:
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.ipv6.conf.all.forwarding
    value: 1
