---
- name: ensure systemd-timesyncd is disabled
  systemd:
    name: systemd-timesyncd
    enabled: no
    state: stopped

- name: install ntp packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
    - ntp-doc
    - ntpdate
    - ntpstat

- name: enable and start ntp daemon
  systemd:
    name: ntp
    enabled: yes
    state: started
    daemon_reload: yes
