---
- name: ensure common packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: ensure vim is default editor
  alternatives:
    name: editor
    path: /usr/bin/vim.basic

- name: ensure default locale is installed
  locale_gen:
    name: "{{ default_locale }}"
    state: present

- name: ensure default locale is set
  command: "/usr/bin/localectl set-locale LANG={{ default_locale }}"
  changed_when: false

- name: set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin

- name: create ffmwu custom config dir
  file:
    path: /home/admin/.config
    state: directory
    owner: admin
    group: admin
    mode: 0750

- name: configure dummy module to load on system boot
  template:
    src: modules_load_dummy.conf.j2
    dest: /etc/modules-load.d/dummy.conf
    owner: root
    group: root
    mode: 0644

- name: configure dummy module options
  template:
    src: modprobe_dummy.conf.j2
    dest: /etc/modprobe.d/dummy.conf
    owner: root
    group: root
    mode: 0644

- name: load dummy module
  modprobe:
    name: "dummy"
    state: present

- name: manage apt auto upgrades
  template:
    src: apt-20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: 0644
    owner: root
    group: root

- name: manage apt unattended upgrades
  template:
    src: apt-50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: 0644
    owner: root
    group: root
