---
- name: ensure common packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: ensure vim is default editor
  alternatives:
    name: editor
    path: /usr/bin/vim.basic

- name: ensure default locale is installed
  locale_gen:
    name: "{{ default_locale }}"
    state: present

- name: ensure default locale is set
  command: "/usr/bin/localectl set-locale LANG={{ default_locale }}"
  changed_when: false

- name: set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin

- name: create ffmwu custom config dir
  file:
    path: /home/admin/.config
    state: directory
    owner: admin
    group: admin
    mode: 0750
