---
- name: create fastd intragate directories
  file:
    path: "/etc/fastd/{{ item.0.id }}igvpn-{{ item.1.mtu }}"
    state: directory
    mode: 0755
  with_subelements:
    - "{{ meshes }}"
    - fastd.intragate.instances

- name: create fastd peer intragate directories
  file:
    path: "/etc/fastd/{{ item.0.id }}igvpn-{{ item.1.mtu }}/peers"
    state: directory
    mode: 0755
    owner: admin
    group: admin
  with_subelements:
    - "{{ meshes }}"
    - fastd.intragate.instances

- name: clone fastd peer intragate repos
  git:
    repo: "{{ item.1.peers.repo }}"
    dest: "/etc/fastd/{{ item.0.id }}igvpn-{{ item.1.mtu }}/peers"
    version: "{{ item.1.peers.version }}"
    update: no
  with_subelements:
    - "{{ meshes }}"
    - fastd.intragate.instances
  become: false

- name: template fastd mesh config
  template:
    src: fastd-intragate.conf.j2
    dest: "/etc/fastd/{{ item.0.id }}igvpn-{{ item.1.mtu }}/fastd.conf"
  notify: restart fastd intragate instances
  with_subelements:
    - "{{ meshes }}"
    - fastd.intragate.instances

- name: write fastd intragate secret
  template:
    src: fastd-secret.conf.j2
    dest: "/etc/fastd/{{ item.0.id }}igvpn-{{ item.1.mtu }}/secret.conf"
  notify: restart fastd intragate instances
  with_subelements:
    - "{{ meshes }}"
    - fastd.intragate.instances

- name: configure systemd unit fastd@
  systemd:
    name: "fastd@{{ item.0.id }}igvpn-{{ item.1.mtu }}"
    enabled: yes
    state: started
  with_subelements:
    - "{{ meshes }}"
    - fastd.intragate.instances
