---
- name: install packages
  apt:
    state: present
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 21600
  with_items:
    - build-essential
    - ecdsautils
    - gawk
    - git
    - haveged
    - libncurses5-dev
    - libssl-dev
    - pkg-config
    - subversion
    - unzip
    - zlib1g-dev
