---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart fastd-nginx
  systemd:
    name: nginx.service
    state: restarted

- name: restart fastd-exporter
  systemd:
    name: fastd-exporter.service
    state: restarted

- name: restart fastd mesh instances
  systemd:
    name: "fastd@{{ item.0.id }}vpn-{{ item.1.mtu }}"
    state: restarted
  loop: "{{ meshes | subelements('fastd.nodes.instances') }}"
