---

- name: Check DNS entries and target distribution
  assert:
    that:
      - "dns_host_ipv4_address in ansible_all_ipv4_addresses"
      - "dns_host_ipv6_address in ansible_all_ipv6_addresses"
      - "dns_gate_num_cname == inventory_hostname"
      - "dns_gate_icvpn_cname == inventory_hostname"
      - "ansible_distribution == 'Debian'"
      - "ansible_distribution_major_version == '9'"

- name: Test root access for admin account
  command: "true"
  changed_when: False

- name: Generate SSH keys
  shell: ssh-keygen -b 4096 -t rsa -f /home/admin/.ssh/id_rsa -q -N ""
  args:
    creates: /home/admin/.ssh/id_rsa
