---
- name: assert IPv4 DNS entry
  local_action: shell dig +short A {{ inventory_hostname }} | egrep '^{{ ansible_default_ipv4.address }}'
  changed_when: False

- name: assert IPv6 DNS entry
  local_action: shell dig +short AAAA {{ inventory_hostname }} | egrep '^{{ ansible_default_ipv6.address }}'
  changed_when: False

- name: Test access to admin account
  command: "true"
  changed_when: False

- name: Test root access for admin account
  command: "true"
  changed_when: False
  become: True

- name: Check for correct OS type and version
  fail: msg="unsupported OS type or version - {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
  when:
    - ansible_distribution != "Debian"
    - ansible_distribution_major_version|int != "9"
