---

- name: restart_unifi
  service:
    name: unifi
    state: restarted
    enabled: yes
  become: yes

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
