---
- name: set freifunk sysctl settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ sysctl_settings }}"

- name: create systemd override dir for systemd-sysctl.service
  file:
    path: /etc/systemd/system/systemd-sysctl.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure systemd unit overrides
  template:
    src: systemd_sysctl_service_overrides.j2
    dest: /etc/systemd/system/systemd-sysctl.service.d/override.conf
    owner: root
    group: root
    mode: 0644
