---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart bind9
  systemd:
    name: bind9
    state: restarted

- name: restart stunnel4
  systemd:
    name: stunnel4
    state: restarted
