---
- name: checkout ecdsautils repo
  git: repo=https://github.com/tcatm/ecdsautils.git
       dest=/home/admin/clones/ecdsautils
       version=v0.3.2

- name: create build directory
  file: path=/home/admin/clones/ecdsautils/build state=directory

- name: build ecdsautils
  shell: "{{ item }}"
  args:
    chdir: /home/admin/clones/ecdsautils/build
  with_items:
    - cmake ..
    - make

- name: install ecdsautils to /usr/local/bin
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: True
  with_items:
    - /home/admin/clones/ecdsautils/build/src/ecdsakeygen
    - /home/admin/clones/ecdsautils/build/src/ecdsaverify
    - /home/admin/clones/ecdsautils/build/src/ecdsasign
  become: true
