---
- name: install git packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git

- name: ensure git directory is present
  file:
    path: /home/admin/clones
    state: directory
    mode: 0755
    owner: admin
    group: admin

- name: clone git repositories
  git:
    repo: "{{ item.value.repo_url }}"
    dest: "/home/admin/clones/{{ item.key }}"
    version: "{{ item.value.version }}"
    force: "{{ item.value.force }}"
  with_dict: "{{ common_repos }}"
  become: false
