---
- name: install packages
  package:
    name: python3-netifaces
    state: present

- name: clone respondd repo
  git:
    repo: https://github.com/freifunk-mwu/mesh-announce.git
    dest: /home/admin/clones/mesh-announce
    version: mwu-respondd
    force: yes
  become: false

- name: set respondd vpn flag to false
  when: ffmwu_server_type != "gateway"
  copy:
    content: "False"
    dest: /home/admin/clones/mesh-announce/nodeinfo.d/vpn
  notify:
    - restart respondd

- name: write systemd unit files
  template:
    src: respondd.service.j2
    dest: "/etc/systemd/system/respondd-{{ item.id }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart respondd
  loop: "{{ meshes }}"

- name: configure systemd unit files
  systemd:
    name: "respondd-{{ item.id }}"
    enabled: yes
    state: started
  loop: "{{ meshes }}"
