---
- name: create mesh bridges
  template:
    src: bridge.j2
    dest: "/etc/network/interfaces.d/{{ item.id }}br"
  notify: reload network interfaces
  loop: "{{ meshes }}"

- name: set sysfs variables
  template:
    src: sysfs.j2
    dest: "/etc/sysfs.d/99-{{ item.id }}br.conf"
  loop: "{{ meshes }}"
  notify: activate sysfs variables

- name: flush handlers
  meta: flush_handlers
