---
- name: install fastd packages
  apt:
    name: "{{ item }}"
    state: present
  notify: reload systemd
  with_items:
    - fastd
    - git

- name: mask legacy service fastd
  systemd:
    name: fastd
    masked: yes
