---
- name: install fastd packages
  package:
    name: "{{ item }}"
    state: present
  notify: reload systemd
  with_items:
    - fastd
    - git

- name: mask legacy service fastd
  systemd:
    name: fastd
    masked: yes

- name: write systemd unit fastd@.service
  template:
    src: fastd@.service.j2
    dest: /etc/systemd/system/fastd@.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd
