---
- name: create loopback interface
  template:
    src: loopback.j2
    dest: "/etc/network/interfaces.d/loopback"
  notify: reload network interfaces

- name: create check-anycast.sh
  template:
    src: check-anycast.sh.j2
    dest: "/usr/local/bin/check-anycast.sh"
    owner: root
    group: root
    mode: 0755
  when: "'mail' not in group_names"

- name: create cronjob for check-anycast.sh
  cron:
    name: "check anycast availability"
    minute: "*/1"
    job: "/usr/local/bin/check-anycast.sh > /dev/null 2>&1"
  when: "'mail' not in group_names"
