#!/usr/bin/ansible-playbook
---
- name: Manage DNS Master Servers.
  hosts: dns

  roles:
  - service-nginx
  - nodejs
  - yarn
  - geerlingguy.mysql
  - powerdns.pdns
  - pdns-admin

- name: Manage DNS External Master Server.
  hosts: reis.freifunk-mwu.de

  roles:
  - service-dehydrated
