#!/usr/bin/ansible-playbook

- hosts: ffmwu-gateways
  remote_user: admin
  roles:
    - prerequisites
    - server-repos
    - server-basic
    - git-repos
    - service-haveged
    - service-ntpd
    - kmod-batman
    - network-routetables
    - network-batman
    - network-meshbridge
    - service-dhcpd
    - service-radvd
    - service-fastd-mesh
    - service-fastd-intragate
    - git-fastd-peers
    - network-fastd
    - network-ffrl
    - service-bird
    - service-bird-icvpn
    - service-bird-ffrl
    - service-rclocal
