#!/usr/bin/ansible-playbook

- hosts: ffmwu-gateways
  remote_user: admin
  roles:
  - prerequisites
  - server-apt-repos
  - server-basic
  - users
  - system-sysctl-gateway
  - git-repos
  - service-haveged
  - service-ntpd
  - kmod-batman
  - network-routetables
  - network-batman
  - network-meshbridge
  - network-fastd
  - network-ffrl
  - network-iptables-gateway
  - network-routing
  - service-dhcpd
  - service-nginx
  - service-nginx-firmware
  - service-radvd
  - service-fastd
  - service-fastd-mesh
  - service-fastd-backbone
  - service-tinc
  - service-bird
  - service-bird-icvpn
  - service-bird-ffrl
  - service-bind-slave
  - service-respondd
  - service-vnstat
  - service-nullmailer
