#!/usr/bin/ansible-playbook

- hosts: ffmwu-monitoring
  remote_user: admin
  roles:
  - prerequisites
  - server-apt-repos
  - server-basic
  - users
  - system-sysctl
  - git-repos
  - golang
  - nodejs
  - yarn
  - service-haveged
  - service-ntpd
  - kmod-batman
  - network-routetables
  - network-batman
  - network-meshbridge
  - network-fastd
  - network-routing
  - service-prometheus
  - service-influxdb
  - service-yanic
  - service-nginx
  - service-nginx-meshviewer
  - service-grafana
  - service-fastd
  - service-fastd-backbone
  - service-bird
  - service-bird-lg
  - service-respondd
  - service-nullmailer
