#!/usr/bin/ansible-playbook
---
- name: Webservers
  hosts: www

  roles:
  - service-nginx-wordpress
  - service-nginx-etherpad
  - service-nginx-firmware-selector
  - service-nginx-media
  - service-nginx-mediawiki
  - service-nginx-mitglieder
  - service-nginx-piwigo
  - service-nginx-git-homepage
