---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart systemd unit ffmwu-static-routes
  systemd:
    name: ffmwu-static-routes
    state: restarted

- name: restart systemd unit ffmwu-ip-rules
  systemd:
    name: ffmwu-ip-rules
    state: restarted
