global:
  smtp_from: "admin@freifunk-mwu.de"
  smtp_smarthost: "localhost:25"
  smtp_require_tls: false

route:
  group_by: ['alertname', 'alertstate', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
    - send_resolved: true
      to: "admin@lists.freifunk-mwu.de"
