modules:
  http_2xx:
    prober: http
    http:
  tcp_connect:
    prober: tcp
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  icmp:
    prober: icmp
    icmp:
      preferred_ip_protocol: "ip4"
  icmp6:
    prober: icmp
    icmp:
      preferred_ip_protocol: "ip6"
