---
- name: create fastd mesh interfaces
  template:
    src: fastd-mesh.j2
    dest: "/etc/network/interfaces.d/{{ item.0.id }}VPN-{{ item.1.mtu }}"
  notify: reload network interfaces
  with_subelements:
    - "{{ meshes }}"
    - fastd.nodes.instances

- name: create fastd intragate interfaces
  template:
    src: fastd-intragate.j2
    dest: "/etc/network/interfaces.d/{{ item.0.id }}igVPN-{{ item.1.mtu }}"
  notify: reload network interfaces
  with_subelements:
    - "{{ meshes }}"
    - fastd.intragate.instances

- name: flush handlers
  meta: flush_handlers
