---
- name: create fastd mesh interfaces
  when: ffmwu_server_type == "gateway"
  template:
    src: fastd-mesh.j2
    dest: "/etc/network/interfaces.d/{{ item.0.id }}vpn-{{ item.1.mtu }}"
  notify: reload network interfaces
  with_subelements:
    - "{{ meshes }}"
    - fastd.nodes.instances

- name: create fastd backbone interfaces
  template:
    src: fastd-backbone.j2
    dest: "/etc/network/interfaces.d/{{ item.0.id }}igvpn-{{ item.1.mtu }}"
  notify: reload network interfaces
  with_subelements:
    - "{{ meshes }}"
    - fastd.backbone.instances

- name: flush handlers
  meta: flush_handlers
